version = 3
defaultGlobalExecutorParallelismExpression = "max(2,min(if(is_windows,(cpus/1.6-2),(cpus/1.2-2)),if(is_j9vm,((mem_gb-(if(is_client,0.6,0.2)))/0.4),((mem_gb-(if(is_client,1.2,0.6)))/0.6))))"

[clientSideConfig]

	[clientSideConfig.modifyMaxVDConfig]
		enabled = false

[noTickViewDistance]
	compatibilityMode = false
	maxConcurrentChunkLoads = 2
	maxViewDistance = 32
	
[ioSystem]
	gcFreeChunkSerializer = true

[threadedWorldGen]
	enabled = true