hideType = "RELOADING"
rgbProgress = false
forceClose = false
blockOverlay = false
miniRender = true
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = false
reInitScreen = true
removeOverlayAtEnd = true
earlyPackStatusSend = true
doubleLoad = "FORCE_LOAD"
animationSpeed = 1000.0
aprilFool = "ON_APRIL"
